all: puzzles.hlp puzzles.txt HACKING

preprocessed.but: puzzles.but
	sed 's/PREFIX-/$(BINPREFIX)/g' puzzles.but > preprocessed.but

puzzles.hlp puzzles.txt: preprocessed.but
	halibut --winhelp=puzzles.hlp --text=puzzles.txt preprocessed.but

HACKING: devel.but
	halibut --text=HACKING devel.but

chm: puzzles.hhp
puzzles.hhp: puzzles.but chm.but
	halibut --html puzzles.but chm.but

clean:
	rm -f puzzles.hlp puzzles.txt preprocessed.but HACKING *.html *.hh[pck]
