package name.boyle.chris.sgtpuzzles.config

/** Constants used for preference names/prefixes/values.  */
object PrefsConstants {
    const val CATEGORY_CHOOSER = "gameChooser"
    const val CHOOSER_STYLE_KEY = "chooserStyle"
    const val CATEGORY_THIS_GAME = "thisGame"
    const val CATEGORY_THIS_GAME_DISPLAY_AND_INPUT = "thisGameDisplayAndInput"
    const val PLACEHOLDER_NO_ARROWS = "arrowKeysUnavailable"
    const val PLACEHOLDER_SEND_FEEDBACK = "send_feedback"
    const val SAVED_BACKEND = "savedBackend"
    const val LAST_PARAMS_PREFIX = "last_params_"
    const val STATE_PREFS_NAME = "state"
    const val ORIENTATION_KEY = "orientation"
    const val ARROW_KEYS_KEY_SUFFIX = "ArrowKeys"
    const val LIMIT_DPI_KEY = "limitDpi"
    const val KEYBOARD_BORDERS_KEY = "keyboardBorders"
    const val BRIDGES_SHOW_H_KEY = "bridgesShowH"
    const val UNEQUAL_SHOW_H_KEY = "unequalShowH"
    const val LATIN_SHOW_M_KEY = "latinShowM"
    const val FULLSCREEN_KEY = "fullscreen"
    const val STAY_AWAKE_KEY = "stayAwake"
    const val UNDO_REDO_KBD_KEY = "undoRedoOnKeyboard"
    const val UNDO_REDO_KBD_DEFAULT = true
    const val MOUSE_LONG_PRESS_KEY = "extMouseLongPress"
    const val MOUSE_BACK_KEY = "extMouseBackKey"
    //const val PATTERN_SHOW_LENGTHS_KEY = "patternShowLengths"
    const val COMPLETED_PROMPT_KEY = "completedPrompt"
    const val VICTORY_FLASH_KEY = "victoryFlash"
    const val CONTROLS_REMINDERS_KEY = "controlsReminders"
    const val OLD_PUZZLESGEN_LAST_UPDATE = "puzzlesgen_last_update"
    const val SAVED_COMPLETED_PREFIX = "savedCompleted_"
    const val SAVED_GAME_PREFIX = "savedGame_"
    const val SWAP_L_R_PREFIX = "swap_l_r_"
    const val UNDO_NEW_GAME_SEEN = "undoNewGameSeen"
    const val REDO_NEW_GAME_SEEN = "redoNewGameSeen"
    const val PUZZLESGEN_CLEANUP_DONE = "puzzlesgen_cleanup_done"
    const val AUTO_ORIENT = "autoOrient"
    const val AUTO_ORIENT_DEFAULT = true
    const val NIGHT_MODE_KEY = "nightMode"
    const val SEEN_NIGHT_MODE = "seenNightMode"
    const val SEEN_NIGHT_MODE_SETTING = "seenNightModeSetting"
}